create or replace view SILVER.V_SERVICE_REQUEST_INFRA as
select *
from SILVER.SV_SERVICE_REQUEST
where agency_name in (
  'DEPARTMENT OF TRANSPORTATION',
  'DEPARTMENT OF ENVIRONMENTAL PROTECTION',
  'DEPARTMENT OF SANITATION',
  'DEPARTMENT OF BUILDINGS',
  'DEPARTMENT OF PARKS AND RECREATION'
);
